C     Errors
      INTEGER MPI_SUCCESS
      PARAMETER (MPI_SUCCESS = 0)

C     Communicators
      INTEGER MPI_COMM_WORLD
      PARAMETER (MPI_COMM_WORLD = 0)
      INTEGER MPI_COMM_SELF
      PARAMETER (MPI_COMM_SELF = 1)
      INTEGER MPI_COMM_NULL
      PARAMETER (MPI_COMM_NULL = -1)

C     Datatypes
      INTEGER MPI_INTEGER
      PARAMETER (MPI_INTEGER = 2)
      INTEGER MPI_REAL
      PARAMETER (MPI_REAL = 11)
      INTEGER MPI_DOUBLE_PRECISION
      PARAMETER (MPI_DOUBLE_PRECISION = 12)
      INTEGER MPI_COMPLEX
      PARAMETER (MPI_COMPLEX = 20)
      INTEGER MPI_DOUBLE_COMPLEX
      PARAMETER (MPI_DOUBLE_COMPLEX = 21)

	  INTEGER MPI_LOGICAL
	  PARAMETER (MPI_LOGICAL = 2)

C     Collective ops
      INTEGER MPI_SUM
      PARAMETER (MPI_SUM = 0)
      INTEGER MPI_MAX
      PARAMETER (MPI_MAX = 1)
      INTEGER MPI_MIN
      PARAMETER (MPI_MIN = 2)
      INTEGER MPI_PROD
      PARAMETER (MPI_PROD = 3)
      INTEGER MPI_LAND
      PARAMETER (MPI_LAND = 4)
      INTEGER MPI_BAND
      PARAMETER (MPI_BAND = 5)
      INTEGER MPI_LOR
      PARAMETER (MPI_LOR = 6)
      INTEGER MPI_BOR
      PARAMETER (MPI_BOR = 7)
      INTEGER MPI_LXOR
      PARAMETER (MPI_LXOR = 8)
      INTEGER MPI_BXOR
      PARAMETER (MPI_BXOR = 9)
      INTEGER MPI_MAXLOC
      PARAMETER (MPI_MAXLOC = 10)
      INTEGER MPI_MINLOC
      PARAMETER (MPI_MINLOC = 11)

C     External symbols
      EXTERNAL MPI_WTIME, MPI_WTICK
      REAL*8 MPI_WTIME, MPI_WTICK

C     Requests
      INTEGER MPI_REQUEST_NULL
      PARAMETER (MPI_REQUEST_NULL = -1)

C     Status
      INTEGER MPI_STATUS_SIZE
      PARAMETER (MPI_STATUS_SIZE = 40)
      INTEGER MPI_SOURCE
      INTEGER MPI_TAG
      INTEGER MPI_ERROR
      PARAMETER (MPI_SOURCE = 2)
      PARAMETER (MPI_TAG = 3)
      PARAMETER (MPI_ERROR = 1)
      INTEGER MPI_STATUS_IGNORE(MPI_STATUS_SIZE)
      INTEGER MPI_STATUSES_IGNORE(MPI_STATUS_SIZE)
      COMMON/mpi_fortran_status_ignore/MPI_STATUS_IGNORE
      COMMON/mpi_fortran_statuses_ignore/MPI_STATUSES_IGNORE
